"""Lecture, lab, and hub metadata for DATA 443/643."""

NOTES = [
    {
        "slug": "course-map",
        "week": 1,
        "title": "1.1 Course Map and the Semester Project",
        "lead": "A self-contained LLM course. Week 1 is the base of the stack; next-token NLL is the cost; the project starts now.",
        "slide": "1.1-course-map",
    },
    {
        "slug": "neurons-activations",
        "week": 1,
        "title": "1.2 Neurons, Activations, and Feedforward Nets",
        "lead": "A weighted sum, a nonlinearity, softmax, and an explicit two-ReLU XOR table.",
        "slide": "1.2-neurons-activations",
    },
    {
        "slug": "gradient-descent",
        "week": 1,
        "title": "1.3 Gradient Descent",
        "lead": "Forward, loss, backward, update, and one ReLU unit’s chain rule. That loop is pretraining.",
        "slide": "1.3-gradient-descent",
    },
    {
        "slug": "embeddings",
        "week": 1,
        "title": "1.4 Word Embeddings and Semantic Geometry",
        "lead": "Dense vectors from a corpus window, skip-gram softmax, analogies, and a signed-projection bias probe.",
        "slide": "1.4-embeddings",
    },
    {
        "slug": "lab-1-xor-embeddings",
        "week": 1,
        "title": "Lab 1: XOR, Autograd, and a Tiny Embedding Space",
        "lead": "PyTorch tensors, a two-layer net on XOR, then cosine and a bias probe on constructed 2-D vectors.",
    },
    {
        "slug": "project-overview",
        "week": 1,
        "title": "Project Overview",
        "lead": "The semester is a measured system plus, for graduate students, a short paper reproduction.",
    },
    {
        "slug": "sequence-rnns",
        "week": 2,
        "title": "2.1 Sequential Models and RNNs",
        "lead": "A shared cell, then an RNN-LM: next-token softmax from the hidden state.",
        "slide": "2.1-sequence-rnns",
    },
    {
        "slug": "vanishing-gradients",
        "week": 2,
        "title": "2.2 Vanishing and Exploding Gradients",
        "lead": "BPTT sums copies of the shared matrix. If the largest |eigenvalue| is below 1, early tokens stop training.",
        "slide": "2.2-vanishing-gradients",
    },
    {
        "slug": "lstm-gru",
        "week": 2,
        "title": "2.3 LSTMs and GRUs",
        "lead": "An additive cell path. Copy when forget is open and input is closed. GRU is two gates.",
        "slide": "2.3-lstm-gru",
    },
    {
        "slug": "lab-2-long-range",
        "week": 2,
        "title": "Lab 2: Long-Range Memory",
        "lead": "Copy the first bit at the end: RNN versus LSTM, plus a gradient-norm check.",
    },
    {
        "slug": "attention-need",
        "week": 3,
        "title": "3.1 From Recurrence to Attention",
        "lead": "The seq2seq bottleneck, then a path of length one at cost T squared.",
        "slide": "3.1-attention-need",
    },
    {
        "slug": "self-attention",
        "week": 3,
        "title": "3.2 Self-Attention (Q, K, V)",
        "lead": "Scaled dots, softmax over keys, mix values. Multi-head, then a causal mask.",
        "slide": "3.2-self-attention",
    },
    {
        "slug": "transformer-block",
        "week": 3,
        "title": "3.3 The Transformer Block",
        "lead": "Positions, residual highways, a token-wise MLP, encoder versus decoder.",
        "slide": "3.3-transformer-block",
    },
    {
        "slug": "gpt-bert",
        "week": 3,
        "title": "3.4 GPT and BERT",
        "lead": "Same block. Causal next-token versus masked tokens. Contextual, not a static table.",
        "slide": "3.4-gpt-bert",
    },
    {
        "slug": "lab-3-self-attention",
        "week": 3,
        "title": "Lab 3: Self-Attention by Hand",
        "lead": "One head by hand, a heatmap, then a causal mask — and why zero is the wrong fill.",
    },
    {
        "slug": "multimodal-foundations",
        "week": 4,
        "title": "4.1 Multimodal Foundations",
        "lead": "Five jobs: represent, align, fuse, translate, co-learn. CLIP scores; concat fuses.",
        "slide": "4.1-multimodal-foundations",
    },
    {
        "slug": "vision-transformers",
        "week": 4,
        "title": "4.2 Vision Transformers",
        "lead": "Non-overlapping patches, a linear map, positions, no causal mask.",
        "slide": "4.2-vision-transformers",
    },
    {
        "slug": "contrastive-zeroshot",
        "week": 4,
        "title": "4.3 Contrastive Learning and Zero-Shot Transfer",
        "lead": "InfoNCE wants the diagonal. Zero-shot is nearest prompt, not a trained C-way head.",
        "slide": "4.3-contrastive-zeroshot",
    },
    {
        "slug": "lab-4-patches-contrastive",
        "week": 4,
        "title": "Lab 4: Patches and a Tiny Contrastive Loss",
        "lead": "Flatten non-overlapping patches, then InfoNCE on four pairs, both as a heatmap.",
    },
    {
        "slug": "clip",
        "week": 5,
        "title": "5.1 CLIP",
        "lead": "Two towers and a cosine. CLIP scores pairs; it does not decode a sentence.",
        "slide": "5.1-clip",
    },
    {
        "slug": "blip",
        "week": 5,
        "title": "5.2 BLIP and Captioning",
        "lead": "CoCa adds a decoder. BLIP also filters the web: ITC, ITM, and a language-model loss.",
        "slide": "5.2-blip",
    },
    {
        "slug": "retrieval-bias",
        "week": 5,
        "title": "5.3 Retrieval, Bias, and Robustness",
        "lead": "recall@k in both directions, an occupation probe, and a typographic miss.",
        "slide": "5.3-retrieval-bias",
    },
    {
        "slug": "lab-5-toy-clip",
        "week": 5,
        "title": "Lab 5: Retrieval in a Toy CLIP Space",
        "lead": "Rank images and texts in 2-D, then a gender–occupation probe.",
    },
    {
        "slug": "audio-spectrograms",
        "week": 6,
        "title": "6.1 Waveforms, Spectrograms, and Time–Frequency Tokens",
        "lead": "STFT frames, not 16 kHz samples. Patch the picture the way ViT patched pixels.",
        "slide": "6.1-audio-spectrograms",
    },
    {
        "slug": "audio-encoders",
        "week": 6,
        "title": "6.2 Audio Encoders and Speech Models",
        "lead": "Whisper transcribes (GPT-style decoder, no CTC). CLAP retrieves. Same spectrogram, different head.",
        "slide": "6.2-audio-encoders",
    },
    {
        "slug": "fusion-scarcity",
        "week": 6,
        "title": "6.3 Fusion, Unified Embeddings, and Data Scarcity",
        "lead": "Early, late, or cross-attention. Concat grows width. Paired audio is scarce.",
        "slide": "6.3-fusion-scarcity",
    },
    {
        "slug": "lab-6-spectrograms",
        "week": 6,
        "title": "Lab 6: A Spectrogram and a Tiny Fusion",
        "lead": "STFT of a sine mixture, patch it, then concat versus add two modalities.",
    },
    {
        "slug": "scaling-laws",
        "week": 7,
        "title": "7.1 Scaling Laws",
        "lead": "Kaplan power laws, then Chinchilla: GPT-3 was 1.7 tokens/parameter, not 20.",
        "slide": "7.1-scaling-laws",
    },
    {
        "slug": "mixture-of-experts",
        "week": 7,
        "title": "7.2 Mixture of Experts",
        "lead": "Mixtral: 8 experts stored, top-2 active. Collapse is a dense net in disguise.",
        "slide": "7.2-mixture-of-experts",
    },
    {
        "slug": "efficiency-deploy",
        "week": 7,
        "title": "7.3 Compression and Deployment",
        "lead": "Prune, quantize, distill, then speculative decoding at serving time.",
        "slide": "7.3-efficiency-deploy",
    },
    {
        "slug": "lab-7-scale-quantize",
        "week": 7,
        "title": "Lab 7: A Scaling Curve and Int8",
        "lead": "Fit a toy power law, then quantize a weight matrix and measure error.",
    },
    {
        "slug": "sft-instructions",
        "week": 8,
        "title": "8.1 Supervised Fine-Tuning and Instruction Data",
        "lead": "Mask the prompt. SFT copies answers; Week 9 is preferences.",
        "slide": "8.1-sft-instructions",
    },
    {
        "slug": "continual-forgetting",
        "week": 8,
        "title": "8.2 Continual Learning and Forgetting",
        "lead": "Train on task B and task A slips. Replay, freeze, or isolate the change.",
        "slide": "8.2-continual-forgetting",
    },
    {
        "slug": "lora-adapters",
        "week": 8,
        "title": "8.3 LoRA, Adapters, and Federated Updates",
        "lead": "Train BA, freeze W. r(d+k) trainable, not dk. Merge has no extra decode latency.",
        "slide": "8.3-lora-adapters",
    },
    {
        "slug": "lab-8-lora-forget",
        "week": 8,
        "title": "Lab 8: A Low-Rank Update and a Forgetting Demo",
        "lead": "Factor a 4×4 update, then train XOR then AND and watch the first task drop.",
    },
    {
        "slug": "preference-rewards",
        "week": 9,
        "title": "9.1 Preference Data and Reward Models",
        "lead": "Bradley–Terry on a pair. Chance is log 2. Best-of-n uses the RM without PPO.",
        "slide": "9.1-preference-rewards",
    },
    {
        "slug": "rlhf",
        "week": 9,
        "title": "9.2 RLHF",
        "lead": "Three stages. Only PPO samples the current policy. β=0 is reward hacking.",
        "slide": "9.2-rlhf",
    },
    {
        "slug": "dpo",
        "week": 9,
        "title": "9.3 Direct Preference Optimization",
        "lead": "Same pairs. Implicit r = β log(π/π_ref). Z(x) cancels. Offline.",
        "slide": "9.3-dpo",
    },
    {
        "slug": "lab-9-preferences",
        "week": 9,
        "title": "Lab 9: Pairwise Preferences and a Toy DPO Loss",
        "lead": "Rank two completions, train a tiny reward head, then a DPO-style logistic on logits.",
    },
    {
        "slug": "red-teaming",
        "week": 10,
        "title": "10.1 Red-Teaming and Safety Evaluation",
        "lead": "A rate on a fixed probe list. HarmBench is 510 behaviors. Rerun after the patch.",
        "slide": "10.1-red-teaming",
    },
    {
        "slug": "editing-unlearning",
        "week": 10,
        "title": "10.2 Editing and Unlearning",
        "lead": "Locate, then a rank-one write. Neighbors and paraphrases are the method.",
        "slide": "10.2-editing-unlearning",
    },
    {
        "slug": "raft-memory",
        "week": 10,
        "title": "10.3 RAFT and Memory-Augmented Models",
        "lead": "Train with gold plus distractors. Week 14 is the RAG stack; this hour is the reader.",
        "slide": "10.3-raft-memory",
    },
    {
        "slug": "lab-10-edit-retrieve",
        "week": 10,
        "title": "Lab 10: Edit a Toy Fact, Then Retrieve It",
        "lead": "Overwrite one key in a lookup table, then compare parametric recall to a retrieved snippet.",
    },
    {
        "slug": "gan-idea",
        "week": 11,
        "title": "11.1 Generative Adversarial Nets",
        "lead": "Give up on p(x). Sample in one pass. Bayes D is 1/2 where G parked.",
        "slide": "11.1-gan-idea",
    },
    {
        "slug": "gan-training",
        "week": 11,
        "title": "11.2 Training Dynamics",
        "lead": "Minimax J. Non-saturating −log D(G(z)). A 99% D is often a dead G.",
        "slide": "11.2-gan-training",
    },
    {
        "slug": "mode-collapse",
        "week": 11,
        "title": "11.3 Mode Collapse and Evaluation",
        "lead": "92/8 is collapse. 47/53 is covered. G’s loss has no missing-mode term.",
        "slide": "11.3-mode-collapse",
    },
    {
        "slug": "lab-11-toy-gan",
        "week": 11,
        "title": "Lab 11: A One-Dimensional GAN Sketch",
        "lead": "Two Gaussians as data. Watch a tiny generator miss a mode.",
    },
    {
        "slug": "diffusion-forward",
        "week": 12,
        "title": "12.1 The Forward Process",
        "lead": "Jump to x_t in one shot. α-bar from 1 to 0. The kernel is not learned.",
        "slide": "12.1-diffusion-forward",
    },
    {
        "slug": "diffusion-reverse",
        "week": 12,
        "title": "12.2 The Reverse Process",
        "lead": "MSE on the noise you added. T reverse steps. Lab 12 uses the oracle mean.",
        "slide": "12.2-diffusion-reverse",
    },
    {
        "slug": "latent-conditioning",
        "week": 12,
        "title": "12.3 Latent Diffusion and Text Conditioning",
        "lead": "CS231N: 12× fewer latent cells. CFG: s=1 is still conditional.",
        "slide": "12.3-latent-conditioning",
    },
    {
        "slug": "lab-12-denoise",
        "week": 12,
        "title": "Lab 12: Noise a Point, Then Take One Reverse Step",
        "lead": "A 2-D schedule, a known score, one denoising update.",
    },
    {
        "slug": "chain-of-thought",
        "week": 13,
        "title": "13.1 Chain-of-Thought",
        "lead": "Ask for steps before the answer. Intermediate tokens can carry scratch work.",
        "slide": "13.1-chain-of-thought",
    },
    {
        "slug": "self-consistency-tot",
        "week": 13,
        "title": "13.2 Self-Consistency and Tree-of-Thoughts",
        "lead": "Sample several traces and vote. Search a tree of partial thoughts when one path is not enough.",
        "slide": "13.2-self-consistency-tot",
    },
    {
        "slug": "faithfulness",
        "week": 13,
        "title": "13.3 Faithfulness of Explanations",
        "lead": "A correct final answer can sit on invented steps. Process and outcome are different claims.",
        "slide": "13.3-faithfulness",
    },
    {
        "slug": "lab-13-reasoning",
        "week": 13,
        "title": "Lab 13: Direct Answers, Traces, and a Majority Vote",
        "lead": "Compare short answers to step traces on arithmetic, then vote, then flag an unfaithful trace.",
    },
    {
        "slug": "rag-pipeline",
        "week": 14,
        "title": "14.1 Retrieval-Augmented Generation",
        "lead": "Index documents, retrieve chunks, then generate with those chunks in context.",
        "slide": "14.1-rag-pipeline",
    },
    {
        "slug": "react-tools",
        "week": 14,
        "title": "14.2 ReAct and Tool Use",
        "lead": "Thought, action, observation. The model calls a tool instead of guessing the lookup.",
        "slide": "14.2-react-tools",
    },
    {
        "slug": "eval-presentations",
        "week": 14,
        "title": "14.3 Evaluating Applications and Giving the Talk",
        "lead": "Citation, uncertainty, and a measured demo. The presentation is part of the method.",
        "slide": "14.3-eval-presentations",
    },
    {
        "slug": "lab-14-toy-rag",
        "week": 14,
        "title": "Lab 14: A Five-Document RAG Loop",
        "lead": "Embed toy snippets, retrieve for a query, then write an answer that cites a chunk id.",
    },
    {
        "slug": "exam-review",
        "week": 15,
        "title": "15.1 Exam Review",
        "lead": "Four modules, one stack. The exam asks you to connect a method to a measurement.",
        "slide": "15.1-exam-review",
    },
]

BY_SLUG = {n["slug"]: n for n in NOTES}

# One primary classroom video per lecture. Title includes a watch cue.
VIDEOS = {
    "course-map": (
        "Karpathy: Intro to Large Language Models (0:00–8:00 in class; finish 0:00–20:00 as homework)",
        "https://www.youtube.com/watch?v=zjkBMFhNj_g",
    ),
    "neurons-activations": (
        "3Blue1Brown: But what is a neural network? (~19 min)",
        "https://www.youtube.com/watch?v=aircAruvnKk",
    ),
    "gradient-descent": (
        "3Blue1Brown: Gradient descent, how neural networks learn (~21 min)",
        "https://www.youtube.com/watch?v=IHZwWFHWa-w",
    ),
    "embeddings": (
        "StatQuest: Word Embedding and Word2Vec, Clearly Explained (~16 min)",
        "https://www.youtube.com/watch?v=viZrOnJclY0",
    ),
    "sequence-rnns": (
        "StatQuest: Recurrent Neural Networks, Clearly Explained (~21 min)",
        "https://www.youtube.com/watch?v=AsNTP8Kwu80",
    ),
    "vanishing-gradients": (
        "Stanford CS224N: Simple and LSTM RNNs (watch the vanishing/exploding segment)",
        "https://www.youtube.com/watch?v=0LixFSa7yts",
    ),
    "lstm-gru": (
        "StatQuest: Long Short-Term Memory (LSTM), Clearly Explained (~21 min)",
        "https://www.youtube.com/watch?v=YCzL96nL7j0",
    ),
    "attention-need": (
        "3Blue1Brown: But what is a GPT? Visual intro to transformers (~27 min)",
        "https://www.youtube.com/watch?v=wjZofJX0v4M",
    ),
    "self-attention": (
        "3Blue1Brown: Attention in transformers, step-by-step (~26 min)",
        "https://www.youtube.com/watch?v=eMlx5fFNoYc",
    ),
    "transformer-block": (
        "Umar Jamil: Transformer explained (architecture + code; watch the block walkthrough)",
        "https://www.youtube.com/watch?v=bCz4OMemCcA",
    ),
    "gpt-bert": (
        "Karpathy: Let's build GPT (watch through the first attention implementation)",
        "https://www.youtube.com/watch?v=kCc8FmEb1nY",
    ),
    "multimodal-foundations": (
        "Yannic Kilcher: OpenAI CLIP, Connecting Text and Images (watch the two-tower setup)",
        "https://www.youtube.com/watch?v=T9XSU0pKX2E",
    ),
    "vision-transformers": (
        "Umar Jamil: Vision Transformer explained (watch the patch embedding section)",
        "https://www.youtube.com/watch?v=j6kuzuy2ZZo",
    ),
    "contrastive-zeroshot": (
        "Yannic Kilcher: OpenAI CLIP (InfoNCE batch and zero-shot prompts)",
        "https://www.youtube.com/watch?v=T9XSU0pKX2E",
    ),
    "clip": (
        "Yannic Kilcher: OpenAI CLIP, Connecting Text and Images (full paper)",
        "https://www.youtube.com/watch?v=T9XSU0pKX2E",
    ),
    "blip": (
        "What's AI: OpenAI's Whisper Model Explained (encoder–decoder analog; pair with the BLIP paper)",
        "https://www.youtube.com/watch?v=uFOkMme19Zs",
    ),
    "retrieval-bias": (
        "Yannic Kilcher: OpenAI CLIP (prompting, retrieval, and failure modes in the second half)",
        "https://www.youtube.com/watch?v=T9XSU0pKX2E",
    ),
    "audio-spectrograms": (
        "Valerio Velardo: Short-Time Fourier Transform explained (Sound of AI)",
        "https://www.youtube.com/watch?v=-Yxj3yfvY-4",
    ),
    "audio-encoders": (
        "What's AI: OpenAI's Whisper Model Explained (~12 min)",
        "https://www.youtube.com/watch?v=uFOkMme19Zs",
    ),
    "fusion-scarcity": (
        "Yannic Kilcher: OpenAI CLIP (coordinated towers as a fusion baseline)",
        "https://www.youtube.com/watch?v=T9XSU0pKX2E",
    ),
    "scaling-laws": (
        "Karpathy: Intro to Large Language Models (scaling and pretraining after 20:00)",
        "https://www.youtube.com/watch?v=zjkBMFhNj_g",
    ),
    "mixture-of-experts": (
        "Karpathy: Deep Dive into LLMs like ChatGPT (internals 20:11–26:01; routing on the board)",
        "https://www.youtube.com/watch?v=7xTGNNLPyMI",
    ),
    "efficiency-deploy": (
        "Umar Jamil: LoRA explained (small deltas at deploy time; pair with the quantization section)",
        "https://www.youtube.com/watch?v=PXWYUTMt-AU",
    ),
    "sft-instructions": (
        "Karpathy: Intro to Large Language Models (assistant / SFT, watch 14:14–21:05)",
        "https://www.youtube.com/watch?v=zjkBMFhNj_g",
    ),
    "continual-forgetting": (
        "Umar Jamil: LoRA explained (why a thin adapter forgets less than full FT)",
        "https://www.youtube.com/watch?v=PXWYUTMt-AU",
    ),
    "lora-adapters": (
        "Umar Jamil: LoRA, explained visually + PyTorch from scratch",
        "https://www.youtube.com/watch?v=PXWYUTMt-AU",
    ),
    "preference-rewards": (
        "Karpathy: Intro to Large Language Models (RLHF / preferences, 21:05–25:43)",
        "https://www.youtube.com/watch?v=zjkBMFhNj_g",
    ),
    "rlhf": (
        "Karpathy: Intro to Large Language Models (RLHF loop, 21:05–25:43)",
        "https://www.youtube.com/watch?v=zjkBMFhNj_g",
    ),
    "dpo": (
        "Karpathy: Deep Dive into LLMs like ChatGPT (preference / RLHF, 2:48:26–3:09:39)",
        "https://www.youtube.com/watch?v=7xTGNNLPyMI",
    ),
    "red-teaming": (
        "Karpathy: Intro to Large Language Models (limitations/security, 45:43–58:37)",
        "https://www.youtube.com/watch?v=zjkBMFhNj_g",
    ),
    "editing-unlearning": (
        "Karpathy: Deep Dive into LLMs (knowledge / hallucination, 1:20:32–1:41:46)",
        "https://www.youtube.com/watch?v=7xTGNNLPyMI",
    ),
    "raft-memory": (
        "Karpathy: Intro to Large Language Models (tools/retrieval, 27:43–33:32)",
        "https://www.youtube.com/watch?v=zjkBMFhNj_g",
    ),
    "gan-idea": (
        "Stanford CS231N: Generative models (GAN setup; 2017 lecture 13)",
        "https://www.youtube.com/watch?v=5WoItGTWV54",
    ),
    "gan-training": (
        "Stanford CS231N: Generative models (training dynamics of G vs D)",
        "https://www.youtube.com/watch?v=5WoItGTWV54",
    ),
    "mode-collapse": (
        "Stanford CS231N: Generative models (mode collapse / evaluation)",
        "https://www.youtube.com/watch?v=5WoItGTWV54",
    ),
    "diffusion-forward": (
        "Umar Jamil: How diffusion models work — explanation and code (forward process)",
        "https://www.youtube.com/watch?v=I1sPXkm2NH4",
    ),
    "diffusion-reverse": (
        "Umar Jamil: How diffusion models work — explanation and code (reverse / loss)",
        "https://www.youtube.com/watch?v=I1sPXkm2NH4",
    ),
    "latent-conditioning": (
        "Umar Jamil: Coding Stable Diffusion (watch 0:00–45:00: VAE, CLIP, UNet)",
        "https://www.youtube.com/watch?v=ZBKpAp_6TGI",
    ),
    "chain-of-thought": (
        "Karpathy: Intro to Large Language Models (reasoning / system-2 remarks)",
        "https://www.youtube.com/watch?v=zjkBMFhNj_g",
    ),
    "self-consistency-tot": (
        "Karpathy: Deep Dive into LLMs like ChatGPT (sampling several traces)",
        "https://www.youtube.com/watch?v=7xTGNNLPyMI",
    ),
    "faithfulness": (
        "Karpathy: Deep Dive into LLMs like ChatGPT (why a fluent trace can still be wrong)",
        "https://www.youtube.com/watch?v=7xTGNNLPyMI",
    ),
    "rag-pipeline": (
        "Karpathy: Intro to Large Language Models (retrieval and tools)",
        "https://www.youtube.com/watch?v=zjkBMFhNj_g",
    ),
    "react-tools": (
        "Karpathy: Intro to Large Language Models (tool-use demo in the second half)",
        "https://www.youtube.com/watch?v=zjkBMFhNj_g",
    ),
    "eval-presentations": (
        "Simon Peyton Jones: How to give a great research talk (watch 0:00–20:00)",
        "https://www.youtube.com/watch?v=sT_-owjKIbA",
    ),
    "exam-review": (
        "Karpathy: Intro to Large Language Models (full recap of the stack)",
        "https://www.youtube.com/watch?v=zjkBMFhNj_g",
    ),
}

VIDEO_EXTRA = {
    "course-map": (
        "MIT 6.S191 Lecture 1: perceptron through loss and gradient descent (homework, ~17:20–44:22)",
        "https://www.youtube.com/watch?v=ErnWZxJovaM",
    ),
    "gpt-bert": (
        "CodeEmporium: BERT Neural Network — EXPLAINED!",
        "https://www.youtube.com/watch?v=xI0HHN5XKDo",
    ),
    "gradient-descent": (
        "3Blue1Brown: What is backpropagation really doing? (~14 min, after class)",
        "https://www.youtube.com/watch?v=Ilg3gGewQ5U",
    ),
    "lstm-gru": (
        "StatQuest: Gated Recurrent Units (GRU), Clearly Explained",
        "https://www.youtube.com/watch?v=tOuXgORsXJ4",
    ),
}

WEEKS = {
    1: {
        "label": "Module 1 — Neural networks and word embeddings",
        "lectures": ["course-map", "neurons-activations", "gradient-descent", "embeddings"],
        "labs": [("lab-1-xor-embeddings", False)],
        "readings": [
            ("Goodfellow, Bengio, Courville: Deep feedforward networks, Ch. 6 opening and §6.1 XOR", "https://www.deeplearningbook.org/contents/mlp.html"),
            ("Nielsen, Neural Networks and Deep Learning, Ch. 1 (gradient descent; stop before long MNIST)", "http://neuralnetworksanddeeplearning.com/chap1.html"),
            ("Jurafsky & Martin, Speech and Language Processing, Ch. 5 Embeddings (draft of 19 Aug 2026)", "https://web.stanford.edu/~jurafsky/slp3/5.pdf"),
            ("Mikolov et al. 2013, Efficient estimation of word representations, §§1–3", "https://arxiv.org/abs/1301.3781"),
            ("Stanford CS224N: word vectors and neural nets (copy intuitions; skip the skip-gram Jacobian)", "https://stanford.edu/class/cs224n/"),
            ("CS231N notes: neuron, backprop as gates, SGD", "https://cs231n.github.io/neural-networks-1/"),
        ],
        "discussion": [
            "Intrinsic vs. extrinsic evaluation of embeddings: which number belongs in a project report, and which one is for debugging?",
            "Name one way embedding geometry can encode a stereotype. What would you measure with the Lab 1 projection?",
            "Why can this course skip DATA 641 and 642 and still start from neurons this week?",
            "Goodfellow’s two-ReLU XOR vs. Lab 1’s 33-parameter MLP: what did the extra units buy you that the table already showed?",
        ],
    },
    2: {
        "label": "Module 1 — Sequence models: RNNs, LSTMs, and GRUs",
        "lectures": ["sequence-rnns", "vanishing-gradients", "lstm-gru"],
        "labs": [("lab-2-long-range", False)],
        "readings": [
            ("Goodfellow, Bengio, Courville: Sequence Modeling, Ch. 10 opening (vanilla RNN; stop before recursive nets)", "https://www.deeplearningbook.org/contents/rnn.html"),
            ("Pascanu, Mikolov, Bengio 2013: On the difficulty of training recurrent neural networks (clipping)", "https://arxiv.org/abs/1211.5063"),
            ("Hochreiter and Schmidhuber 1997: Long short-term memory (cite, do not assign the whole paper)", "https://www.bioinf.jku.at/publications/older/2604.pdf"),
            ("Stanford CS224N W26 L4: language models and RNNs (copy intuitions; skip NMT)", "https://web.stanford.edu/class/cs224n/slides_w26/cs224n-2026-lecture04-rnnlm.pdf"),
            ("Stanford CS231N 2025 L7: RNNs, BPTT, singular values (copy the computational-graph form)", "https://cs231n.stanford.edu/slides/2025/lecture_7.pdf"),
            ("CMU 11-785 L14: stability, memory, and the LSTM cell (copy the eigenvalue slogan)", "https://deeplearning.cs.cmu.edu/F24/document/slides/lec14.recurrent.pdf"),
            ("Understanding LSTM networks (Olah), after 2.3", "https://colah.github.io/posts/2015-08-Understanding-LSTMs/"),
        ],
        "discussion": [
            "Why is a shared recurrent cell a better default than a wider n-gram table or a fixed-window MLP?",
            "Clipping and truncated BPTT both appear in RNN papers. Which problem does each one actually address?",
            "If the forget gate is 1 and the input gate is 0, what happens to the cell, and to the gradient along that path? Why does that not mean LSTMs solved vanishing gradients?",
            "Lab 2 copies the first bit. What would a vanished gradient look like in your table as T grows, and what would you report in a project?",
        ],
    },
    3: {
        "label": "Module 1 — Attention and transformers",
        "lectures": ["attention-need", "self-attention", "transformer-block", "gpt-bert"],
        "labs": [("lab-3-self-attention", False)],
        "readings": [
            ("Vaswani et al., Attention is all you need (architecture; skip the appendix training tricks)", "https://arxiv.org/abs/1706.03762"),
            ("Bahdanau, Cho, Bengio 2015: Neural machine translation by jointly learning to align (cite the reread)", "https://arxiv.org/abs/1409.0473"),
            ("Jurafsky & Martin, Speech and Language Processing, Ch. 9 The Transformer (SLP3 draft)", "https://web.stanford.edu/~jurafsky/slp3/9.pdf"),
            ("Jurafsky & Martin, Ch. 10 Masked and Generative Language Models (SLP3 draft)", "https://web.stanford.edu/~jurafsky/slp3/10.pdf"),
            ("Stanford CS224N W26 L5: attention and transformers (copy the bottleneck; skip NMT training)", "https://web.stanford.edu/class/cs224n/slides_w26/cs224n-2026-lecture05-transformers.pdf"),
            ("CMU 11-711: attention and transformers (copy scaled dots, multi-head, the causal mask)", "https://cmu-l3.github.io/anlp-spring2025/static_files/anlp-s2025-05-attention-transformers.pdf"),
            ("Princeton COS 484 L8 and L10: encoder vs decoder, then GPT vs BERT", "https://princeton-nlp.github.io/cos484/lectures/L8_sp26.pdf"),
            ("Illustrated transformer (Alammar), after 3.3", "https://jalammar.github.io/illustrated-transformer/"),
        ],
        "discussion": [
            "Path length 1 versus cost T squared: which one is the reason we left RNNs, and which one is the reason Week 7 exists?",
            "Why mix values rather than keys? What goes wrong in Lab 3 if you softmax over the wrong axis?",
            "GPT versus BERT: which mask, which loss, and which one would you pick if the demo must stream tokens?",
            "If you drop positional encodings, which two sentences become the same set? Why is that fatal for language?",
        ],
    },
    4: {
        "label": "Module 2 — Multimodal foundations and vision transformers",
        "lectures": ["multimodal-foundations", "vision-transformers", "contrastive-zeroshot"],
        "labs": [("lab-4-patches-contrastive", False)],
        "readings": [
            ("Baltrušaitis, Ahuja, Morency: Multimodal machine learning (the five challenges)", "https://arxiv.org/abs/1705.09406"),
            ("CMU 11-777: Multimodal Machine Learning (joint vs coordinated; copy slogans, skip DCCA)", "https://cmu-multicomp-lab.github.io/mmml-course/fall2023/"),
            ("Dosovitskiy et al., An image is worth 16x16 words (ViT; architecture, not the full scaling appendix)", "https://arxiv.org/abs/2010.11929"),
            ("Stanford CS231N 2025 L8: attention and transformers, including ViT patchification", "https://cs231n.stanford.edu/slides/2025/lecture_8.pdf"),
            ("Oord et al., Contrastive predictive coding (InfoNCE; cite the loss, skip the audio CPC setup)", "https://arxiv.org/abs/1807.03748"),
            ("Stanford CS231N 2025 L16: vision and language (CLIP contrastive, zero-shot, a photo of)", "https://cs231n.stanford.edu/slides/2025/lecture_16.pdf"),
            ("Radford et al., CLIP (Week 5 owns the paper; this week is the loss and zero-shot)", "https://arxiv.org/abs/2103.00020"),
        ],
        "discussion": [
            "Search a photo gallery with a typed query: why is a coordinated space the default, and what breaks in a joint concat model?",
            "A classifier ViT sees all patches at once. Why is a GPT causal mask the wrong extra?",
            "InfoNCE treats the rest of the batch as negatives. What goes wrong if every caption is the word photo?",
            "Linear probe versus zero-shot: which one needs a labeled C-way training set, and which one needs the text tower?",
        ],
    },
    5: {
        "label": "Module 2 — Vision–language models (CLIP and BLIP)",
        "lectures": ["clip", "blip", "retrieval-bias"],
        "labs": [("lab-5-toy-clip", False)],
        "readings": [
            ("Radford et al., CLIP (towers, InfoNCE, zero-shot; skip the full WIT appendix)", "https://arxiv.org/abs/2103.00020"),
            ("Stanford CS231N 2025 L16: CLIP is a similarity score; CoCa adds a decoder", "https://cs231n.stanford.edu/slides/2025/lecture_16.pdf"),
            ("Li et al., BLIP (ITC + ITM + LM, and the bootstrap filter)", "https://arxiv.org/abs/2201.12086"),
        ],
        "discussion": [
            "CLIP retrieves; BLIP can write. Which one belongs in a captioning project, and which loss is the reason?",
            "A batch of 8 versus 1024: what did you add, and what did CS231N say still fails (mug in grass)?",
            "Name one retrieval probe you would run before ranking people or jobs, and one typographic failure you would log.",
            "ITM versus ITC: when is a binary matcher the right tool and a batch softmax the wrong one?",
        ],
    },
    6: {
        "label": "Module 2 — Audio and cross-modal integration",
        "lectures": ["audio-spectrograms", "audio-encoders", "fusion-scarcity"],
        "labs": [("lab-6-spectrograms", False)],
        "readings": [
            ("Stanford CS224S 2025 L2: spectrogram as spectrum plus time", "https://web.stanford.edu/class/cs224s/semesters/2025-spring/lecture-slides/224s.25.lec2.pdf"),
            ("Stanford CS224S 2025 L11: Whisper architecture, 30 s chunks, no CTC", "https://web.stanford.edu/class/cs224s/semesters/2025-spring/lecture-slides/224s.25.lec11.pdf"),
            ("Radford et al., Whisper (weak supervision, encoder–decoder)", "https://arxiv.org/abs/2212.04356"),
            ("Elizalde et al., CLAP (CLIP for audio)", "https://arxiv.org/abs/2206.04769"),
            ("CMU 11-777: multimodal fusion (early / late / cross-attention)", "https://cmu-multicomp-lab.github.io/mmml-course/fall2023/schedule/"),
        ],
        "discussion": [
            "Why is a spectrogram a more natural transformer input than the raw waveform at 16 kHz?",
            "Whisper versus CLAP: both take spectrograms. Which head do you want for subtitles, and which for a typed search?",
            "Name one fusion choice you would defend if audio is often missing at test time.",
            "Audio is 64-D and vision is 256-D. What linear map lets you add them, and what map do you need after a concat?",
        ],
    },
    7: {
        "label": "Module 3 — Scaling, efficiency, and deployment",
        "lectures": ["scaling-laws", "mixture-of-experts", "efficiency-deploy"],
        "labs": [("lab-7-scale-quantize", False)],
        "readings": [
            ("Kaplan et al., Scaling laws for neural language models", "https://arxiv.org/abs/2001.08361"),
            ("Stanford CS224N 2025 L9: GPT-3 tokens versus Chinchilla", "https://web.stanford.edu/class/cs224n/slides_w25/cs224n-2025-lecture09-pretraining.pdf"),
            ("Hoffmann et al., Chinchilla / training compute-optimal LLMs", "https://arxiv.org/abs/2203.15556"),
            ("Stanford CS336 2025 L4: Mixtral 8 experts, top-2 active", "https://qihongruan.github.io/cs336/lec04.html"),
        ],
        "discussion": [
            "GPT-3 was 175B on 300B tokens. Who does Chinchilla pick at the same FLOPs, and why?",
            "If you can 10× parameters or 10× tokens but not both, which does Chinchilla push you toward?",
            "Mixtral stores 8 MLPs and runs 2. What did you just train if the router always picks expert 2?",
            "Quantization is not a free lunch. What would you measure besides perplexity?",
        ],
    },
    8: {
        "label": "Module 3 — SFT, continual learning, and adapters",
        "lectures": ["sft-instructions", "continual-forgetting", "lora-adapters"],
        "labs": [("lab-8-lora-forget", False)],
        "readings": [
            ("Stanford CS224N 2025 L10: instruction finetuning as the first InstructGPT stage", "https://web.stanford.edu/class/archive/cs/cs224n/cs224n.1254/slides_w25/cs224n-2025-lecture10-instruction-tunining-rlhf.pdf"),
            ("Wei et al., Finetuned language models are zero-shot learners (FLAN)", "https://arxiv.org/abs/2109.01652"),
            ("Stanford CS224N 2025 L11: PEFT and LoRA (merge, swap, no extra decode latency)", "https://web.stanford.edu/class/archive/cs/cs224n/cs224n.1254/slides_w25/cs224n-2025-lecture11-adapatation.pdf"),
            ("Hu et al., LoRA", "https://arxiv.org/abs/2106.09685"),
        ],
        "discussion": [
            "Why can a model that next-token-predicts Wikipedia still fail a polite instruction?",
            "Why mask the prompt in the SFT loss?",
            "Replay still moves W. LoRA does not. Which claim belongs in a hospital adapter write-up?",
            "When is LoRA the wrong tool (name one setting)?",
        ],
    },
    9: {
        "label": "Module 3 — RLHF and direct preference optimization",
        "lectures": ["preference-rewards", "rlhf", "dpo"],
        "labs": [("lab-9-preferences", False)],
        "readings": [
            ("Stanford CS224N 2025 L10: RM, RLHF, DPO (SFT was Week 8)", "https://web.stanford.edu/class/archive/cs/cs224n/cs224n.1254/slides_w25/cs224n-2025-lecture10-instruction-tunining-rlhf.pdf"),
            ("Ouyang et al., InstructGPT (the three-stage stack)", "https://arxiv.org/abs/2203.02155"),
            ("Rafailov et al., Direct Preference Optimization", "https://arxiv.org/abs/2305.18290"),
            ("Dubois et al., AlpacaFarm (best-of-n is a strong baseline)", "https://arxiv.org/abs/2305.14387"),
        ],
        "discussion": [
            "Best-of-n uses the RM and never trains π_θ. When is that enough for a project, and when is it not?",
            "If r_w = r_l always, what is the RM loss, and what did the head fail to learn?",
            "Why is π_ref the SFT model rather than the raw pretrained LM?",
            "DPO skips PPO. What can a fixed pair file still not invent?",
        ],
    },
    10: {
        "label": "Module 3 — Safety, editing, and retrieval-augmented training",
        "lectures": ["red-teaming", "editing-unlearning", "raft-memory"],
        "labs": [("lab-10-edit-retrieve", False)],
        "readings": [
            ("Stanford CS336 2025 L12: HarmBench / HELM safety as rates, not vibes", "https://qihongruan.github.io/cs336/lec12.html"),
            ("Stanford CS224N 2025 L13: parametric knowledge versus open-book / RAG", "https://web.stanford.edu/class/cs224n/slides_w25/cs224n-2025-lecture13-QA.pdf"),
            ("Meng et al., ROME / locating and editing factual associations", "https://arxiv.org/abs/2202.05262"),
            ("Zhang et al., RAFT (train the reader with retrieved context)", "https://arxiv.org/abs/2403.10131"),
        ],
        "discussion": [
            "4/40 failed. After a DPO patch, which cells do you rerun, and why is over-refusal a separate column?",
            "Edit success 8/10 and neighbor 2/10. Did the write isolate the fact?",
            "Gold is ranked 3rd and k=2. Whose bug is that — retrieval or the reader?",
            "A salary in a PDF versus a ROME write: which memory did you update, and when is the PDF the better tool?",
        ],
    },
    11: {
        "label": "Module 4 — Generative models I: GANs",
        "lectures": ["gan-idea", "gan-training", "mode-collapse"],
        "labs": [("lab-11-toy-gan", False)],
        "readings": [
            ("Stanford CS231N 2025 L13: GANs give up on p(x) and sample in one pass", "https://cs231n.stanford.edu/slides/2025/lecture_13.pdf"),
            ("Goodfellow et al., Generative adversarial nets", "https://arxiv.org/abs/1406.2661"),
            ("Salimans et al., Improved techniques for training GANs", "https://arxiv.org/abs/1606.03498"),
        ],
        "discussion": [
            "G(z)=+2 always. What is Bayes D(+2) and D(−2) on equal spikes at ±2?",
            "Why is a 99% discriminator often a dead generator?",
            "92 fakes on A and 8 on B: which lab rule fires, and why can lossG still look small?",
            "Name one query a GAN cannot answer that an explicit likelihood model can.",
        ],
    },
    12: {
        "label": "Module 4 — Generative models II: diffusion",
        "lectures": ["diffusion-forward", "diffusion-reverse", "latent-conditioning"],
        "labs": [("lab-12-denoise", False)],
        "readings": [
            ("Stanford CS231N 2025 L14: diffusion, LDM (D=8, C=16), classifier-free guidance", "https://cs231n.stanford.edu/slides/2025/lecture_14.pdf"),
            ("Ho et al., Denoising diffusion probabilistic models", "https://arxiv.org/abs/2006.11239"),
            ("Rombach et al., Latent diffusion / Stable Diffusion", "https://arxiv.org/abs/2112.10752"),
        ],
        "discussion": [
            "Why sample x_t from q(x_t | x_0) instead of walking t Markov steps in the loss?",
            "If ε_θ equals the true ε, what should one reverse mean do in the 12.1 cartoon?",
            "s=1 versus s=12: which is “no text,” and what happens to variety?",
            "256×256×3 versus 32×32×16: whose bug is a slow sampler if you still denoise pixels?",
        ],
    },
    13: {
        "label": "Module 4 — Reasoning and chain-of-thought",
        "lectures": ["chain-of-thought", "self-consistency-tot", "faithfulness"],
        "labs": [("lab-13-reasoning", False)],
        "readings": [
            ("Wei et al., Chain-of-thought prompting", "https://arxiv.org/abs/2201.11903"),
            ("Wang et al., Self-consistency", "https://arxiv.org/abs/2203.11171"),
            ("Yao et al., Tree of Thoughts", "https://arxiv.org/abs/2305.10601"),
        ],
        "discussion": [
            "Self-consistency can raise accuracy without making any one trace more faithful. Why?",
            "When would you refuse to put a CoT trace in a user-facing product?",
        ],
    },
    14: {
        "label": "Module 4 — Tools, RAG, and final presentations",
        "lectures": ["rag-pipeline", "react-tools", "eval-presentations"],
        "labs": [("lab-14-toy-rag", False)],
        "readings": [
            ("Lewis et al., RAG", "https://arxiv.org/abs/2005.11401"),
            ("Yao et al., ReAct", "https://arxiv.org/abs/2210.03629"),
        ],
        "discussion": [
            "What failure does RAG not fix if the retrieved chunk is itself wrong?",
            "In a project talk, which number belongs on the slide: a demo GIF, or an ablation?",
        ],
    },
    15: {
        "label": "Final exam and remaining talks",
        "lectures": ["exam-review"],
        "readings": [
            ("Course hub: weeks 1–14 notes", "data-643.html"),
        ],
        "discussion": [
            "Pick one method from Modules 1–4 and name the measurement you would report, not the architecture.",
            "Remaining talks: as posted on Canvas. Bring one failure case, not only the best run.",
        ],
    },
}
